<?php use Phalcon\Tag; ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<?php $this->tag->setDefaults(array(
	"sourceBook"=>"MM"
));?>

<?= $this->tag->form("monster/add"); ?>

 <p>
    <label for="name">Name</label>
    <?= $this->tag->textField(array("name", 'onKeyUp'=>'updatePlural()')) ?>
 </p>
 
  <p>
    <label for="plural">Plural Form</label>
    <?= $this->tag->textField("plural") ?>
 </p>

 <p>
    <label for="email">CR</label>
    <?= $this->tag->select(array("cr", $validCRs)) ?>
 </p>
 
 <p>
    <label for="terrains">Terrains</label>
    <?= $this->tag->select(array("terrains[]", $validTerrains, "multiple"=>true)) ?>
 </p>
 
 <p>
    <label for="sourceBook">Source Book</label>
    <?= $this->tag->textField("sourceBook") ?>
 </p>
 
 <p>
    <label for="page">Page Number</label>
    <?= $this->tag->textField("page") ?>
 </p>

 <p>
    <?= $this->tag->submitButton("Add") ?>
 </p>

<?= $this->tag->endForm() ?>

<script>
function updatePlural() {
	val = $('#name').val();
	if (val != '') val += 's';
	$('#plural').val(val);
}
</script>