<?php use Phalcon\Tag; ?>
<?php $this->tag->setDefaults(array(
	"characterLevels"=>"1,1,1,1"
));?>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<?= $this->tag->form(array("encounter/generate", "method"=>"POST", "onsubmit"=>"generateEncounters()")); ?>

 <p>
    <label for="terrain">Terrain</label>
    <?= $this->tag->select(array("terrain", $validTerrains)) ?>
 </p>
 
 <p>
    <label for="difficulty">Difficulty</label>
    <?= $this->tag->select(array("difficulty", $validDifficulties)) ?>
 </p>
 
 <p>
    <label for="characterLevels">Party (comma separated list of character levels)</label>
    <?= $this->tag->textField("characterLevels") ?>
 </p>
	
 <p>
    <?= $this->tag->submitButton("Generate") ?>
 </p>

<?= $this->tag->endForm() ?>
<hr/>
<div id="encounters"></div>


<script>
function generateEncounters() {
	event.preventDefault();
	url = "encounter/generate";
	characterLevels = $("#characterLevels").val().split(",");
	$.each(characterLevels, function(i,v){
		characterLevels[i] = parseInt(v);
	});
	data = {
		characterLevels: characterLevels,
		terrain: $("#terrain").val(),
		difficulty: $("#difficulty").val()
	};
	$.ajax({
		url:url,
		data:data,
		type:"POST",
		success:function(data) {
			$("#encounters").html(data);
		}
	});
}
</script>