<?php use Phalcon\Tag; ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<?= $this->tag->form(array("encounter/generate", "method"=>"POST", "onsubmit"=>"generateEncounters()")); ?>

 <p>
    <label for="terrain">Terrain</label>
    <?= $this->tag->select(array("terrain", $validTerrains)) ?>
 </p>
	
 <p>
    <?= $this->tag->submitButton("Generate") ?>
 </p>

<?= $this->tag->endForm() ?>
<hr/>
<div id="encounters"></div>


<script>
function generateEncounters() {
	event.preventDefault();
	url = "generate";
	data = {
		characterLevels: [1,1,1,1],
		terrain: $("#terrain").children("option").filter(":selected").text(),
		difficulty: 4
	};
	$.ajax({
		url:url,
		data:data,
		type:"POST",
		success:function(data) {
			$("#encounters").html(data);
		}
	});
}
</script>