<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<div id="encounters"></div>

<script>
$(document).ready(function(){
	generateEncounters();
})

function generateEncounters() {
	url = "generate";
	data = {
		characterLevels: [1,1,1,1]
	};
	$.ajax({
		url:url,
		data:data,
		type:"POST",
		success:function(data) {
			$("#encounters").html(data);
		}
	});
}
</script>